### ISSUE TITLE
IndexError with pytest's fixtures.py

### ISSUE THREAD

**Issue by blueyed** [asottile/pyupgrade#144]
```
% pyupgrade --py3-only --keep-percent-format src/_pytest/fixtures.py
Traceback (most recent call last):
  File "…/Vcs/pytest/.venv/bin/pyupgrade", line 11, in <module>
    sys.exit(main())
  File "…/Vcs/pytest/.venv/lib/python3.7/site-packages/pyupgrade.py", line 1428, in main
    ret |= fix_file(filename, args)
  File "…/Vcs/pytest/.venv/lib/python3.7/site-packages/pyupgrade.py", line 1402, in fix_file
    contents_text = _fix_py3_plus(contents_text)
  File "…/Vcs/pytest/.venv/lib/python3.7/site-packages/pyupgrade.py", line 1244, in _fix_py3_plus
    _replace_call(tokens, i, end, func_args, template)
  File "…/Vcs/pytest/.venv/lib/python3.7/site-packages/pyupgrade.py", line 1171, in _replace_call
    src = tmpl.format(args=arg_strs, rest=rest)
IndexError: list index out of range
```
`print(repr(tmpl), repr(arg_strs), repr(rest))` shows:

> 'raise {args[1]}.with_traceback({args[2]})' ['*err'] ''

**Comment by asottile** [comment]
hmm yes, reraise with starargs should get skipped -- should be an easy fix

**Comment by asottile** [comment]
thanks for the report!  This is in 1.17.1
