### ISSUE TITLE
cant run pyupgrade. I get a ModuleNotFoundError when I try

### ISSUE THREAD

**Issue by dusty-dusty** [asottile/pyupgrade#203]
ModuleNotFoundError: No module named 'ctypes.windll' 

PS D:\Coding\Python Projects\image\fishing> pipupgrade -    
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\pipupgrade.exe\__main__.py", line 5, in <module>
  File "c:\program files\python37\lib\site-packages\pipupgrade\__init__.py", line 7, in <module>
    from pipupgrade.__main__ import main
  File "c:\program files\python37\lib\site-packages\pipupgrade\__main__.py", line 5, in <module>
    from pipupgrade.commands import command as main
  File "c:\program files\python37\lib\site-packages\pipupgrade\commands\__init__.py", line 9, in <module>
    from pipupgrade.commands.helper import (
  File "c:\program files\python37\lib\site-packages\pipupgrade\commands\helper.py", line 8, in <module>
    from pipupgrade.commands.util       import cli_format
  File "c:\program files\python37\lib\site-packages\pipupgrade\commands\util.py", line 2, in <module>
    from pipupgrade.cli.parser import get_args
    from pipupgrade.cli.parser import get_args
  File "c:\program files\python37\lib\site-packages\pipupgrade\cli\parser.py", line 25, in <module>
    _cli.format(__name__,        _cli.RED),
  File "c:\program files\python37\lib\site-packages\pipupgrade\cli\util.py", line 52, in format
    kernel32 = import_handler("ctypes.windll.kernel32")
  File "c:\program files\python37\lib\site-packages\pipupgrade\util\imports.py", line 18, in import_handler
    handler = _HANDLER_REGISTRY[name]
  File "c:\program files\python37\lib\site-packages\pipupgrade\util\imports.py", line 8, in __missing__
    module = __import__(module_name, {}, {}, [handler_name])
ModuleNotFoundError: No module named 'ctypes.windll'

**Comment by dusty-dusty** [comment]
python -m pip install --upgrade pip
Requirement already up-to-date: pip in c:\program files\python37\lib\site-packages (19.2.3)

**Comment by asottile** [comment]
you're confusing pipupgrade with pyupgrade
