### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by hugovk** [asottile/pyupgrade#207]
Running pyupgrade with no arguments on [this file](https://github.com/jazzband/tablib/blob/ca8dbcf9bea46607d22fe205498b4c071c705860/tablib/formats/_jira.py) includes this change:

```diff
 def _serialize_row(row, delimiter='|'):
-    return '%s%s%s' % (delimiter,
+    return '{}{}{}'.format(delimiter,
                        delimiter.join([unicode(item) if item else ' ' for item in row]),
                        delimiter)
```

This starts failing when running tests on Python 2:

```
  File "/private/tmp/tablib/tablib/formats/_jira.py", line 39, in _serialize_row
    delimiter)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 0: ordinal not in range(128)
```

Smaller example:

```python
item = u"\xe5"

print(1)
print("%s%s" % (item, item))  # original line
print(2)
print("{}{}".format(item, item))  # pyupgraded line
print(3)
```

```console
$ pip freeze | grep pyupgrade
pyupgrade==1.24.0
$ python3 --version
Python 3.7.4
$ python3 2.py
1
åå
2
åå
3
$ python2 --version
Python 2.7.16
$ python2 2.py
1
åå
2
Traceback (most recent call last):
  File "2.py", line 6, in <module>
    print("{}{}".format(item, item))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 0: ordinal not in range(128)
```

And it's not a problem with eg. `item = "abc"`

**Comment by asottile** [comment]
yeah this is known -- this is why `--keep-percent-format` was added sadly -- it is however a safe rewrite in python3

**Comment by hugovk** [comment]
Okay, thanks, will use that! Tablib will be dropping Python 2 soonish anyway.
