### ISSUE TITLE
six.reraise: IndexError: list index out of range

### ISSUE THREAD

**Issue by jdufresne** [asottile/pyupgrade#246]
pyupgrade 1.26.0

Minimal test case. Requires using the `--py3-plus` argument.

```
def foo(func, arg):
    et, ev, _ = sys.exc_info()
    six.reraise(et, (ev[0], ev[1] + (" %s %s" % (func, arg))))
```

```
Traceback (most recent call last):
  File ".../venv/bin/pyupgrade", line 10, in <module>
    sys.exit(main())
  File ".../venv/lib64/python3.8/site-packages/pyupgrade.py", line 2318, in main
    ret |= _fix_file(filename, args)
  File ".../venv/lib64/python3.8/site-packages/pyupgrade.py", line 2280, in _fix_file
    contents_text = _fix_py3_plus(contents_text)
  File ".../venv/lib64/python3.8/site-packages/pyupgrade.py", line 1984, in _fix_py3_plus
    _replace_call(tokens, i, end, func_args, template)
  File ".../venv/lib64/python3.8/site-packages/pyupgrade.py", line 1849, in _replace_call
    src = tmpl.format(args=arg_strs, rest=rest)
IndexError: list index out of range
```

Discovered by running on setuptools:

https://github.com/pypa/setuptools/blob/682b6511ac67e021b542e74ce30e13fe52bc2da9/setuptools/command/easy_install.py#L1730-L1735

**Comment by asottile** [comment]
hmmm yes 2-arg reraise (which is not really a useful use of reraise since it loses the traceback info -- which is kind of the point of reraise) -- guess I'll add an exclusion for it?

but in reality the setuptools code always raises a `TypeError` in python 3:

(translated)

```python
import os
import sys


def f():
    os.unlink('dne')


def g():
    try:
        f()
    except Exception:
        et, ev, _ = sys.exc_info()
        vv = (ev[0], ev[1] + (" %s %s" % (func, arg)))
        raise vv.with_traceback(None)

g()
```

```console
$ python3 t.py
Traceback (most recent call last):
  File "t.py", line 11, in g
    f()
  File "t.py", line 6, in f
    os.unlink('dne')
FileNotFoundError: [Errno 2] No such file or directory: 'dne'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "t.py", line 17, in <module>
    g()
  File "t.py", line 14, in g
    vv = (ev[0], ev[1] + (" %s %s" % (func, arg)))
TypeError: 'FileNotFoundError' object is not subscriptable
```

**Comment by jdufresne** [comment]
> guess I'll add an exclusion for it?

This sounds like a good approach to me. If there is nothing that can be reasonably improved, better to leave as is.

**Comment by asottile** [comment]
it can be translated to `raise {arg[1]}.with_traceback(None)` if `arg[2]` is missing -- it'll at least show that the setuptools code is nonsense 🤷‍♂

**Comment by asottile** [comment]
here's what it does now:

```diff
--- t.py.old	2020-01-18 08:20:27.431782088 -0800
+++ t.py	2020-01-18 08:20:32.326228085 -0800
@@ -1,3 +1,3 @@
 def foo(func, arg):
     et, ev, _ = sys.exc_info()
-    six.reraise(et, (ev[0], ev[1] + (" %s %s" % (func, arg))))
+    raise (ev[0], ev[1] + (" {} {}".format(func, arg))).with_traceback(None)
```

this has been released with v1.26.1

**Comment by jdufresne** [comment]
Thanks for quick response!

**Comment by asottile** [comment]
I suspect you'll want to change that code to `raise et(...)` instead fwiw
