### ISSUE TITLE
NotImplementedError on Foo = TypedDict("Foo", {"lsts": List[List[int]]})

### ISSUE THREAD

**Issue by andersk** [asottile/pyupgrade#284]
Running this code through `pyupgrade --py36-plus`:

```python
from typing import List
from typing_extensions import TypedDict

Foo = TypedDict("Foo", {"lsts": List[List[int]]})
```

gives this error:

```console
$ pyupgrade --py36-plus test.py
Traceback (most recent call last):
  File "/tmp/ve/bin/pyupgrade", line 11, in <module>
    load_entry_point('pyupgrade', 'console_scripts', 'pyupgrade')()
  File "/home/anders/python/pyupgrade/pyupgrade.py", line 2491, in main
    ret |= _fix_file(filename, args)
  File "/home/anders/python/pyupgrade/pyupgrade.py", line 2455, in _fix_file
    contents_text = _fix_py36_plus(contents_text)
  File "/home/anders/python/pyupgrade/pyupgrade.py", line 2430, in _fix_py36_plus
    _replace_typed_class(tokens, i, call, types)
  File "/home/anders/python/pyupgrade/pyupgrade.py", line 2360, in _replace_typed_class
    attrs = '\n'.join(f'{indent}{k}: {_unparse(v)}' for k, v in types.items())
  File "/home/anders/python/pyupgrade/pyupgrade.py", line 2360, in <genexpr>
    attrs = '\n'.join(f'{indent}{k}: {_unparse(v)}' for k, v in types.items())
  File "/home/anders/python/pyupgrade/pyupgrade.py", line 2314, in _unparse
    raise NotImplementedError(ast.dump(node))
NotImplementedError: Subscript(value=Name(id='List', ctx=Load()), slice=Index(value=Subscript(value=Name(id='List', ctx=Load()), slice=Index(value=Name(id='int', ctx=Load())), ctx=Load())), ctx=Load())
```

**Comment by asottile** [comment]
thanks for the report!  a small oversight in a new feature on my part -- sorry about that!  should be fixed in v2.2.1
