### ISSUE TITLE
Fails to run on python3.9

### ISSUE THREAD

**Issue by gaborbernat** [asottile/pyupgrade#378]
This is because there is no import removals defined for https://github.com/asottile/pyupgrade/blob/5e32666723/pyupgrade.py#L680-L693, and https://github.com/asottile/pyupgrade/blob/5e32666723/pyupgrade.py#L732 lookup fails. Perhaps instead of ``[]`` it should use ``.get``?

```
venv/bin/pyupgrade --py39-plus src/**.py 
Traceback (most recent call last):
  File "/Users/bgabor8/git/a/venv/bin/pyupgrade", line 8, in <module>
    sys.exit(main())
  File "/Users/bgabor8/git/a/venv/lib/python3.9/site-packages/pyupgrade.py", line 2823, in main
    ret |= _fix_file(filename, args)
  File "/Users/bgabor8/git/a/venv/lib/python3.9/site-packages/pyupgrade.py", line 2770, in _fix_file
    contents_text = _fix_tokens(contents_text, min_version=args.min_version)
  File "/Users/bgabor8/git/a/venv/lib/python3.9/site-packages/pyupgrade.py", line 808, in _fix_tokens
    _fix_import_removals(tokens, i, min_version)
  File "/Users/bgabor8/git/a/venv/lib/python3.9/site-packages/pyupgrade.py", line 732, in _fix_import_removals
    if modname not in IMPORT_REMOVALS[min_version]:
KeyError: (3, 9)
```

**Comment by asottile** [comment]
oops, this is easy to fix at least
