### ISSUE TITLE
PEP 604 happens on independently on the passed Python version

### ISSUE THREAD

**Issue by hynek** [asottile/pyupgrade#392]
Given this code:

```
from __future__ import annotations

from typing import Optional


def f(x: Optional[int]) -> None:
    pass
```

Running `pyupgrade --py39-plus tmp.py` over it gives me:

```
from __future__ import annotations

from typing import Optional


def f(x: int | None) -> None:
    pass
```

Which hilariously will work on pre-3.10, unless you try to use the typing information:

```
Traceback (most recent call last):
  File "/Users/hynek/tmp/tmp.py", line 9, in <module>
    print(typing.get_type_hints(f))
  File "/Users/hynek/.asdf/installs/python/3.9.1/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 1442, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/Users/hynek/.asdf/installs/python/3.9.1/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 277, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/Users/hynek/.asdf/installs/python/3.9.1/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 533, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Update**: I've tried a few more version arguments and I suspect you're only acting on the presence of `from __future__ import annotations`?

**Comment by MarcoGorelli** [comment]
>  I suspect you're only acting on the presence of from __future__ import annotations?

Looks like it:

https://github.com/asottile/pyupgrade/blob/6ee68a06cbfbbf1d69fffa6cda03fe301a706b15/pyupgrade/_plugins/typing_pep604.py#L87-L95

**Comment by asottile** [comment]
If you have code which retrieves typing information at runtime, use the `--keep-runtime-annotations` option [as listed in the README](https://github.com/asottile/pyupgrade#pep-604-typing-rewrites)
