### ISSUE TITLE
IndentationError: unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by MarcoGorelli** [asottile/pyupgrade#407]
To reproduce:
```python
# t.py

from __future__ import annotations

from typing import (
    Sequence,
    Union,
)


def sort_index(
    self,
    ascending: Union[Union[bool, int], Sequence[Union[bool, int]]],
):
    indexer = get_indexer_indexer(
        target, level, ascending, kind, na_position, sort_remaining, key
    )
```

Then:
```console
$ pyupgrade t.py 
Traceback (most recent call last):
  File "/home/marco/tmp/venv/bin/pyupgrade", line 8, in <module>
    sys.exit(main())
  File "/home/marco/tmp/venv/lib/python3.8/site-packages/pyupgrade/_main.py", line 889, in main
    ret |= _fix_file(filename, args)
  File "/home/marco/tmp/venv/lib/python3.8/site-packages/pyupgrade/_main.py", line 837, in _fix_file
    contents_text = _fix_tokens(contents_text, min_version=args.min_version)
  File "/home/marco/tmp/venv/lib/python3.8/site-packages/pyupgrade/_main.py", line 481, in _fix_tokens
    tokens = src_to_tokens(contents_text)
  File "/home/marco/tmp/venv/lib/python3.8/site-packages/tokenize_rt.py", line 68, in src_to_tokens
    for (
  File "/usr/lib/python3.8/tokenize.py", line 512, in _tokenize
    raise IndentationError(
  File "<tokenize>", line 15
    )
    ^
IndentationError: unindent does not match any outer indentation level
```

Removing either the `indexer = ` line, or the `ascending: ` annotation, makes `pyupgrade` pass. Keeping them both in, it fails.

Spotted in pandas, when commit 78371ccbd8744326e8535ac8bb9a661b073dfd88 meant that `pyupgrade` could no longer be run on `pandas/core/generic.py` without `--keep-runtime-typing`

----

version info:
```console
$ pip freeze | grep pyupgrade
pyupgrade==2.10.0
$ pip freeze | grep tokenize-rt
tokenize-rt==4.1.0
$ python --version
Python 3.8.5
```

**Comment by asottile** [comment]
looks like a bug with the union collapser (perhaps due to recursive collapsing), this is the intermediate state:

```python
from __future__ import annotations

from typing import (
    Sequence,
    Union,
)


def sort_index(
    self,
    ascending: bool | int, Sequencebool | int],
):
    indexer = get_indexer_indexer(
        target, level, ascending, kind, na_position, sort_remaining, key
    )
```

**Comment by asottile** [comment]
yeah this `arg_offset` is never found after the first argument is rewritten -- probably need a smarter way to parse tuples: https://github.com/asottile/pyupgrade/blob/0dd2d79e7606a36cd0a82561404b4e8ef17e8715/pyupgrade/_plugins/typing_pep604.py#L41
