### ISSUE TITLE
Crash on frozenset()

### ISSUE THREAD

**Issue by nijel** [asottile/pyupgrade#449]
Pyupgrade crashes on following code:

```py
frozenset()
```

Exception:

```pytb
Traceback (most recent call last):
  File "/home/nijel/weblate/translate/.venv/bin/pyupgrade", line 8, in <module>
    sys.exit(main())
  File "/home/nijel/weblate/translate/.venv/lib/python3.9/site-packages/pyupgrade/_main.py", line 928, in main
    ret |= _fix_file(filename, args)
  File "/home/nijel/weblate/translate/.venv/lib/python3.9/site-packages/pyupgrade/_main.py", line 863, in _fix_file
    contents_text = _fix_plugins(
  File "/home/nijel/weblate/translate/.venv/lib/python3.9/site-packages/pyupgrade/_main.py", line 105, in _fix_plugins
    callbacks = visit(FUNCS, ast_obj, settings)
  File "/home/nijel/weblate/translate/.venv/lib/python3.9/site-packages/pyupgrade/_data.py", line 89, in visit
    for offset, token_func in ast_func(state, node, parent):
  File "/home/nijel/weblate/translate/.venv/lib/python3.9/site-packages/pyupgrade/_plugins/generator_expressions_pep289.py", line 66, in visit_Call
    if _func_condition(node.func) and isinstance(node.args[0], ast.ListComp):
IndexError: list index out of range
```

This started to happen with pyupgrade 2.18.0.

**Comment by asottile** [comment]
heh this is @MarcoGorelli 's new fix -- looks like it needs to check argcount

**Comment by asottile** [comment]
thanks for the report! bump to 2.18.1

**Comment by nijel** [comment]
Thanks for fast fix!

**Comment by MarcoGorelli** [comment]
> heh this is @MarcoGorelli 's new fix -- looks like it needs to check argcount

Thanks both for the fast report and fast fix respectively - next time I'll run changes on a few more large repos to check for test cases I hadn't thought of
