### ISSUE TITLE
Two files that cause pyupgrade to fail

### ISSUE THREAD

**Issue by foolip** [asottile/pyupgrade#465]
Since https://github.com/asottile/pyupgrade/issues/461 was addressed so quickly I thought I'd report two more files where pyupgrade throws an exception. I don't have time to minify them, but it should reproduce with pyupgrade 2.19.2.

The two files:
https://github.com/web-platform-tests/wpt/blob/9096c654c33771806faf9d78bd9e247364ebed5b/tools/third_party/hpack/test/test_huffman.py
https://github.com/web-platform-tests/wpt/blob/9096c654c33771806faf9d78bd9e247364ebed5b/tools/third_party/six/test_six.py

The failures:

> pyupgrade --py36-plus tools/third_party/hpack/test/test_huffman.py

```
Traceback (most recent call last):
  File "/Users/foolip/Library/Python/3.8/bin/pyupgrade", line 10, in <module>
    sys.exit(main())
  File "/Users/foolip/Library/Python/3.8/lib/python/site-packages/pyupgrade/_main.py", line 928, in main
    ret |= _fix_file(filename, args)
  File "/Users/foolip/Library/Python/3.8/lib/python/site-packages/pyupgrade/_main.py", line 872, in _fix_file
    contents_text = _fix_tokens(contents_text, min_version=args.min_version)
  File "/Users/foolip/Library/Python/3.8/lib/python/site-packages/pyupgrade/_main.py", line 498, in _fix_tokens
    _fix_encode_to_binary(tokens, i)
  File "/Users/foolip/Library/Python/3.8/lib/python/site-packages/pyupgrade/_main.py", line 346, in _fix_encode_to_binary
    if is_codec(encoding, 'ascii') or is_codec(encoding, 'utf-8'):
  File "/Users/foolip/Library/Python/3.8/lib/python/site-packages/pyupgrade/_string_helpers.py", line 14, in is_codec
    return codecs.lookup(encoding).name == name
TypeError: lookup() argument must be str, not bytes
```

> pyupgrade --py36-plus tools/third_party/six/test_six.py

```
Traceback (most recent call last):
  File "/Users/foolip/Library/Python/3.8/bin/pyupgrade", line 10, in <module>
    sys.exit(main())
  File "/Users/foolip/Library/Python/3.8/lib/python/site-packages/pyupgrade/_main.py", line 928, in main
    ret |= _fix_file(filename, args)
  File "/Users/foolip/Library/Python/3.8/lib/python/site-packages/pyupgrade/_main.py", line 872, in _fix_file
    contents_text = _fix_tokens(contents_text, min_version=args.min_version)
  File "/Users/foolip/Library/Python/3.8/lib/python/site-packages/pyupgrade/_main.py", line 482, in _fix_tokens
    tokens = src_to_tokens(contents_text)
  File "/Users/foolip/Library/Python/3.8/lib/python/site-packages/tokenize_rt.py", line 68, in src_to_tokens
    for (
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/tokenize.py", line 512, in _tokenize
    raise IndentationError(
  File "<tokenize>", line 959
    assert getattr(six.moves.builtins, 'bytes', str)(my_test) == b"hello"
    ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by asottile** [comment]
the first one is pyupgrade is over-eagerly looking at `.encode('string')` calls -- that one is an easy fix: #466

the second is a variant of #358 and is more difficult to fix (though I imagine you should be able to delete that entire file)

**Comment by foolip** [comment]
Thanks @asottile! I'm not going to run really `pyupgrade` on these files since they're third-party code for us, but I thought I'd still report them in case they were new issues. Thanks for fixing one of them! I won't mind if you close this as a dupe of https://github.com/asottile/pyupgrade/issues/358.

**Comment by asottile** [comment]
ended up being easy enough to fix that particular variant

**Comment by foolip** [comment]
Awesome, thanks @asottile!
