### ISSUE TITLE
NotImplementedError on Python 3.9 when TypedDict contains Literals

### ISSUE THREAD

**Issue by PeterJCLaw** [asottile/pyupgrade#706]
Given:
``` python
from typing import Literal, TypedDict

SomeDict = TypedDict('SomeDict', {
    'value': Literal[2],
    'id': int,
})
```
Running `pyupgrade` crashes:
```
$ pyupgrade --py39-plus demo.py 
Traceback (most recent call last):
  File ".../bin/pyupgrade", line 8, in <module>
    sys.exit(main())
  File ".../lib/python3.9/site-packages/pyupgrade/_main.py", line 498, in main
    ret |= _fix_file(filename, args)
  File ".../lib/python3.9/site-packages/pyupgrade/_main.py", line 429, in _fix_file
    contents_text = _fix_plugins(
  File ".../lib/python3.9/site-packages/pyupgrade/_main.py", line 81, in _fix_plugins
    callback(i, tokens)
  File ".../lib/python3.9/site-packages/pyupgrade/_plugins/typing_classes.py", line 121, in _fix_dict_typed_dict
    end, attrs = _typed_class_replacement(tokens, i, call, types)
  File ".../lib/python3.9/site-packages/pyupgrade/_plugins/typing_classes.py", line 72, in _typed_class_replacement
    attrs = '\n'.join(f'{indent}{k}: {_unparse(v)}' for k, v in types.items())
  File ".../lib/python3.9/site-packages/pyupgrade/_plugins/typing_classes.py", line 72, in <genexpr>
    attrs = '\n'.join(f'{indent}{k}: {_unparse(v)}' for k, v in types.items())
  File ".../lib/python3.9/site-packages/pyupgrade/_plugins/typing_classes.py", line 39, in _unparse
    slice_s = _unparse(node_slice)
  File ".../lib/python3.9/site-packages/pyupgrade/_plugins/typing_classes.py", line 50, in _unparse
    raise NotImplementedError(ast.dump(node))
NotImplementedError: Constant(value=2)
```

**Comment by asottile** [comment]
I think #701 is trying to solve this?

**Comment by PeterJCLaw** [comment]
Ahh, yeah. I'd read the title and assumed that `ast.Constant` was different.
