### ISSUE TITLE
Rewriting `pep 604 typing rewrites` causes error for pydantic+Python3.9

### ISSUE THREAD

**Issue by conao3** [asottile/pyupgrade#763]
Hi, thanks for this project. Thanks to this project, my code base is properly modernized.

I am reporting that I have noticed an error when using pydantic in Python 3.9, even when `from __future__ import annotations`.
I can prevent rewriting with this rule by specifying `--keep-runtime-typing`, but changing `Dict[str, str]` to `dict[str, str]` is still legal in this situation.

On a related note, even when using modern Python, `Optional[str]` and `str | None`, I prefer the former. Since this is a preference, a switch that can disable only the pep604 rewrite rule would address both use cases.

### test.py
```python
from __future__ import annotations
from typing import Any, Optional

import pydantic


class InputBody(pydantic.BaseModel):
    skip: Optional[bool]


def main(arg: dict[str, Any]):
    print(arg)
    inpt = InputBody(**arg)

    print(inpt.dict())


main({"skip": True})
```

### test-pep604.py
```python
from __future__ import annotations
from typing import Any

import pydantic


class InputBody(pydantic.BaseModel):
    skip: bool | None


def main(arg: dict[str, Any]):
    print(arg)
    inpt = InputBody(**arg)

    print(inpt.dict())


main({"skip": True})
```

## repro step
```
$ mkdir test

$ cd test

$ python3.9 -m venv .venv

$ . .venv/bin/activate
(.venv) $ pip install pydantic
Collecting pydantic
  Using cached pydantic-1.10.2-cp39-cp39-macosx_11_0_arm64.whl (2.6 MB)
Collecting typing-extensions>=4.1.0
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Installing collected packages: typing-extensions, pydantic
Successfully installed pydantic-1.10.2 typing-extensions-4.4.0

(.venv) $ python3.9 test.py
{'skip': True}
{'skip': True}

(.venv) $ python3.9 test-pep604.py
Traceback (most recent call last):
  File "/Users/conao/dev/optarc/optarc-bi-runtime/test/test-pep604.py", line 7, in <module>
    class InputBody(pydantic.BaseModel):
  File "pydantic/main.py", line 179, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 399, in pydantic.typing.resolve_annotations
    should not be set on instances of that class. Usage::
  File "/Users/conao/.anyenv/envs/pyenv/versions/3.9.13/lib/python3.9/typing.py", line 292, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/Users/conao/.anyenv/envs/pyenv/versions/3.9.13/lib/python3.9/typing.py", line 554, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by asottile** [comment]
please be a better open source user and search the issue tracker for duplicates next time -- thanks!

**Comment by conao3** [comment]
Sorry, @asottile.

P.S.
As a just follow-up, this is a duplicate of #415
