### ISSUE TITLE
Behaviour change after upgrading '%.4g' to '{:.4g}'

### ISSUE THREAD

**Issue by hugovk** [asottile/pyupgrade#85]
This change https://github.com/hugovk/cartopy/commit/f1c5b7a56acf679a2d624cafb9160bc038463fc2 fails unit tests, which passed before:

```diff
-        return u'%.4g, %.4g (%f\u00b0%s, %f\u00b0%s)' % (x, y, abs(lat),
-                                                         ns, abs(lon), ew)
+        return u'{:.4g}, {:.4g} ({:f}\u00b0{}, {:f}\u00b0{})'.format(x, y, abs(lat),
+                                                                     ns, abs(lon), ew)
```

https://travis-ci.org/hugovk/cartopy/jobs/463956921#L1111

Small example:

```python
Python 3.7.1 (default, Nov  6 2018, 18:45:35)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> x, y = np.array([-969100.0]), np.array([-4457000.0])
>>>
>>> # Before
...
>>> u"%.4g, %.4g" % (x, y)
'-9.691e+05, -4.457e+06'
>>>
>>> # After
...
>>> u"{:.4g}, {:.4g}".format(x, y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported format string passed to numpy.ndarray.__format__
>>>
```

**Comment by asottile** [comment]
I'm inclined to believe this is an issue with `numpy` itself.  `%g` and `{:g}` work the same for builtin types.  A workaround is to use `[0]` it seems?  I'm not all too familiar with `numpy` myself.  float-formatting an array seems wrong to me?

```pycon
>>> '%g' % (numpy.array([1.]),)
'1'
>>> '%g' % ([1.],)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: must be real number, not list
```

```pycon
>>> '{:g}'.format(numpy.array([1.]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported format string passed to numpy.ndarray.__format__
>>> '{:g}'.format(numpy.array([1.][0]))
'1'
```

**Comment by asottile** [comment]
closing this since it appears to be an internal consistency issue specific to numpy ndarrays
